//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayTime
    {
        public int id { get; set; }
        public Nullable<int> movie_id { get; set; }
        public System.DateTime play { get; set; }
        public Nullable<int> total_sits { get; set; }
        public Nullable<int> availble_sits { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
